language: python
python:
    - "3.4"
    - "3.5"
services:
    - redis-server
install:
    - pip install -r requirements/development.txt
script:
    - pep8 .
    - python fastube/manage.py test users posts
notifications:
      slack: fcwps2:prEREpboGWrmcLR8N69ZVJBi
